### ISSUE TITLE
What should we call the UI?

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#10]
The goal of this project is to make shortcodes usable.

Ryan put it well saying something along the lines of - Although shortcodes are a fairly good technical solution, they should never be exposed to users.

So - should probably remove the word 'shortcode' from the UI.

After some brainstorming - i've gone with "content item" but i'm not totally happy with it. 

Heres a dump of the other ideas from hipchat: 
- Section
- snippet
- Content Area
- content area
- Content Module
- content snippet
- Post Item 
- Block
- Item
- Module
- blocks
- embedded item
- embedded object
- add extra content
- add optional content

**Comment by danielbachhuber** [comment]
We're calling it "Shortcake". The admin labels still need some work though.

**Comment by danielbachhuber** [comment]
I'm re-opening this because our media library integration needs much more consideration.

**Comment by roborourke** [comment]
Currently Shortcake replaces 'Add media' with 'Add content'. While I understand the desire to avoid adding too many buttons I think it's better not to change too much from the default WP behaviour. 'Add content' seems too generic, they're already adding content.

I propose leaving 'Add media' as is and adding another button that opens the media frame on the Shortcake UI.

Regarding the button and UI label perhaps 'Add rich content'? Shortcake will only make sense to users who already know what shortcodes are.

**Comment by danielbachhuber** [comment]
@mattheu how do you feel about "Post Element"? and we can keep the Add Media button as "Add Media"?

**Comment by mattheu** [comment]
I like it.

**Comment by danielbachhuber** [comment]
@sanchothefat do you like "Post Elements" ?

**Comment by roborourke** [comment]
Yeah! My main concern was just people wondering what happened to the 'add
media' button, let's go ahead with this name :)

## 

Robert O'Rourke
_mobile:_ +447816329424
_skype: *rob.o.rourke
*web:_ röb.co

**Comment by danielbachhuber** [comment]
I changed "Add Content" back to "Add Media" for the time being.

**Comment by StaggerLeee** [comment]
Will just thank you all here, to not to open new ticket unnecessary. 
I know it is only 5-6 months old, but put it in WP repository, even as Alpha/Beta. I work every day with WP and read things, today was first time I heard about Shortcake. And this by chance too.

Maybe something best for WP for long time. It is well needed, something like this.
There is mainly 3 things in WP I personally never use on any of websites i make. Have no use of them whatsoever.
- Theme Customizer.
- WP native meta box with custom fields.
- And third is this here, WP "standard" management of shortcodes.

It doesnt work, to explain all the time to beginners why they have to be careful when they delete text characters around shortcode parenthesis. It is so Joomla way of dealing with things.

Because of this your project can be something very unique end mega good.
There are some commercial plugins with previews, but non of them is meant for strong community who share snipepts and shortcodes. To closed support forums, to small number of users.

**Comment by danielbachhuber** [comment]
> I know it is only 5-6 months old, but put it in WP repository, even as Alpha/Beta

Yep, on our list of things to do #125

> Maybe something best for WP for long time. It is well needed, something like this.

Glad that it's useful!
