### ISSUE TITLE
Don't process nested content

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#126]
I have a shortcode called [bw_geshi] which takes its input from the $content.
I use it to document code, especially examples of shortcodes.
e.g.
`[bw_geshi lang=html]
Here is some nested content
With a shortcode [oik]
<span>and some more</span> HTML
[/bw_geshi]`

Clicking on the Edit link loses the nested shortcode tags.

**Comment by danielbachhuber** [comment]
> Don't process nested content

Ignoring nested shortcodes seems like the best way to handle this for the time being.

**Comment by roborourke** [comment]
Yep - WordPress by default doesn't process nested shortcodes - that's up to the shortcode implementer to call `do_shortcode()` on their returned content.

**Comment by bfintal** [comment]
I agree, this should be left as is

**Comment by danielbachhuber** [comment]
@bobbingwide Does `inner_content` attribute solve this for you?

**Comment by bobbingwide** [comment]
Hi Daniel, sorry for the big delay. I switched to use 'inner_content' and it worked fine for the [bw_geshi] shortcode, which doesn't expand the content. But when I tried it with my [bw_csv] shortcode then it wasn't good at all. 
Suspect this could be something to do with #317 
I'll add some notes to that issue.

**Comment by danielbachhuber** [comment]
Sounds good, thanks @bobbingwide

**Comment by nikolov-tmw** [comment]
Sorry for resurrecting an old issue, but I believe I shouldn't start a new one, since the problem I'm having is similar.

The problem I'm having is that I need to be able to have shortcodes contained within the `inner_content` field of a shortcode. I agree that you should not process those shortcodes, but you're also using a much simplified version of the regular expression that WordPress' `get_shortcode_regex()` function returns.

It basically uses regex placeholders to match a currently being processed shortcode(as far as I understand it) against it's closing tag. Here:

![regex returned by get_shortcode_regex()](https://nidus.paiyakdev.com/screens/Screenshot-at-2015-07-16_22:50:01.png)

What this does is that it captures any shortcodes that could possibly be contained within a shortcode and just passes them to the `$content` parameter of your shortcode handling function.

In the case of Shortcake, I get undefined, because you're matching anything but `[`.

I'm not aware of whether the same regular expression can be implemented in JavaScript or not, but I think Shortcake should try to stick as much as possible to the WordPress shortcode parsing regular expression.

Thank you for the great work - I definitely love it all! :+1:
