### ISSUE TITLE
Add support for wpautop()

### ISSUE THREAD

**Issue by nturbanov** [wp-shortcake/shortcake#171]
Since there is no possibility to add a TinyMCE field yet, support for wpautop() would be great, ie. a single line break renders a `<br />` and a double line break a `<p>`.

`<?php echo wpautop( $content ); ?>` works in the front-end and the WP editor, but the html tags are visible in the Shortcake textarea, except the very fist opening `<p>` and the very las closing `</p>`.

**Comment by danielbachhuber** [comment]
There's a couple ways you could hack this right now:
1. Hook into the preview actions to add a `<p>` tag before and after.
2. Have some conditional logic in the shortcode that runs the result through `wpautop()` when the context is admin ajax.

I suppose the easiest way to do this would be to run the preview HTML through a filter. It seems messy to have two actions _and_ a filter though.

@mattheu Thoughts?

**Comment by mattheu** [comment]
This is a tricky one.

So I think that this should be handled in the JS as thats where the problem lies - rather than adding a filter.

I _think_ we can fix this by running the content through `switchEditors._wp_Nop` in 2 places. Once when outputting the formatted shortcode. Once when parsing the content from the raw shortcode.

I'm going to open a PR with this - but I am a little concerned that it have other unforseen consequences...

**Comment by danielbachhuber** [comment]
Moving this out of v0.3.0
