### ISSUE TITLE
Call for feedback

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#33]
We're going live in the next couple of days. Any last minute show stoppers people have discovered? What should we call this thing (both as a plugin, and UI labels)?

cc @staylor @tmtrademark @mboynes @nickdaugherty @nickgernert @johnbillion @bcampeau @mattheu @davisshaver

**Comment by jeremyfelt** [comment]
Totally digging the possibilities of this. Worked right away with the shortcode I'm using to pull in blocks on business.wsu.edu and I'm loving it.
- Talk about the "Add Content" button in the documentation. I forgot to rewatch the video and spent a bit of time troubleshooting why "Add My Shortcode Label" wasn't appearing above TinyMCE. :)
- My crazier shortcode doesn't work immediately, but it relies on enough JS being in the right place that it isn't really the target audience.
- I haven't dug too deep yet, but I'd like to add my own input templates - search existing content, etc...
- Strange things seem to happen with existing shortcodes that were not originally added when Shortcode UI was available. Rather than bringing up an edit button, or not rendering in tinyMCE at all, it shows the shortcode but does not allow you to edit unless you go to text mode. Screenshot below.

![screen shot 2014-11-04 at 9 57 19 am](https://cloud.githubusercontent.com/assets/286171/4905028/459aefbc-644c-11e4-9334-1b0b41d50aef.png)

Overall, +1 for MVP from me. I'm looking forward to using this.

**Comment by danielbachhuber** [comment]
> Talk about the "Add Content" button in the documentation. I forgot to rewatch the video and spent a bit of time troubleshooting why "Add My Shortcode Label" wasn't appearing above TinyMCE. :)

Do you think it makes sense to combine the two? What should we call the UI?

> I haven't dug too deep yet, but I'd like to add my own input templates - search existing content, etc..

You can actually do this now — and we're hoping to add integrations with existing form builder tools.
