### ISSUE TITLE
Problem with Quotation marks in text fields

### ISSUE THREAD

**Issue by taccz** [wp-shortcake/shortcake#342]
Hi, when I use " in text field, it doesn't save. Can you fix it? Thanks

**Comment by danielbachhuber** [comment]
This is how I see the problem manifest itself:

![image](https://cloud.githubusercontent.com/assets/36432/7884060/1aebe386-05d0-11e5-8c1a-a72c3fcf2c71.png)

For our shortcode with a text field, I can actually use the `"` in the field through the UI, but it doesn't get properly passed to the shortcode.

I suspect the problem is ultimately the same as we're trying to address with #322

**Comment by danielbachhuber** [comment]
We [chatted about this](https://wordpress.slack.com/archives/feature-shortcode/p1433791051000087) a bit today. I'm reclassifying as an upstream bug. Here's the corresponding core ticket: https://core.trac.wordpress.org/ticket/15694

Shortcode UI actually works fine — quoted attributes are properly rendered in the shortcode UI form.

**Comment by paulkarpenko** [comment]
It sounds like the wordpress team is kicking this back to developers: "Since this issue does not affect the core shortcodes, this has become purely an API problem for plugin developers". 

Is there a workaround for this with the current functionality of wordpress core? I've got to figure out a way to allow double quotes in our shortcode inputs so any help would be appreciated. Thanks.

**Comment by danielbachhuber** [comment]
> It sounds like the wordpress team is kicking this back to developers: "Since this issue does not affect the core shortcodes, this has become purely an API problem for plugin developers".

Yeah. This is called "solving the problem by not solving the problem"

> Is there a workaround for this with the current functionality of wordpress core?

Use the `$content` part to the shortcode for your data with double quotes:

```
[my-shortcode]This is "quoted"[/my-shortcode]
```

**Comment by danielbachhuber** [comment]
This is addressed on master with #496. You can use an `encode` argument to encode shortcode attributes. You'll either need to unencode in your shortcode callback, or run your arguments through `shortcode_atts()` for automatic filtering.
