### ISSUE TITLE
Documentation refresh

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#389]
Let's refresh our documentation across the board, particularly PHPdoc and JS docs.

**Comment by danielbachhuber** [comment]
@jrfnl When you have a moment, I'd love to hear what documentation you _expect_ to see, so we have a target to work towards.

**Comment by jrfnl** [comment]
@danielbachhuber Chat in Slack or want some input here ?

**Comment by danielbachhuber** [comment]
> Chat in Slack or want some input here ?

Input here would be great — thanks!

**Comment by jrfnl** [comment]
Ok, here are some ideas for the wiki documentation on how plugins should integrate Shortcake UI:
- a list of all array index keys which are supported and what they are used for, both for the top level array as well as the individual field arrays
- for each of those the variable type expected, if there are limitations (i.e. "the following values are recognized, anything else will be disregarded") and what the default will be
- for each of those whether setting it is required or optional or even superfluous in certain cases
- a number of examples - at the very least one of each for self-closing shortcode, shortcode with content
- some screenshots of the effects which can be archieved

For an arbitrary example (without screenshots, but then again different kind of library), have a look at the new TGMPA configuration webpage - http://tgmpluginactivation.com/configuration/
Input on how we could improve that is of course welcome too ;-)

I presume I won't have to give input on the PHPDoc/JSDoc side of things ? Basics there are of course that all functions and methods should have a docblock which includes a description of what it does and when it's used, `@since` tag, `@param` tags for all parameters and if there is a return value a `@return` tag.

**Comment by danielbachhuber** [comment]
For reference, WP inline documentation standards: https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/

**Comment by jrfnl** [comment]
http://www.phpdoc.org/docs/latest/index.html ;-)

**Comment by danielbachhuber** [comment]
PHPDoc is in a good place now. I want to pick up JS doc as a part of this issue in v0.6.0

**Comment by danielbachhuber** [comment]
We had #16 for JS docs, so closing this issue in favor of that.
