### ISSUE TITLE
Start using the regex that WordPress uses in PHP for shortcode parsing

### ISSUE THREAD

**Issue by nikolov-tmw** [wp-shortcake/shortcake#392]
Right now a very simple regular expression is used for parsing shortcodes, compared to what WordPress natively uses in `get_shortcode_regex()`. This breaks things like shortcodes within the `inner_content`(which is more or less a common use case).

I've managed to import the regex over to JS and I'm going to create a pull request here with the adjustments I've done.

**Comment by danielbachhuber** [comment]
:+1:

**Comment by khromov** [comment]
@nikolov-tmw Was there any issues with this? Don't see a PR for it.

**Comment by nikolov-tmw** [comment]
It's right here - https://github.com/fusioneng/Shortcake/pull/393 .
I'm supposed to write some Unit tests, but never got around to it. I'll try to allocate some time next week to write the tests and update(if necessary) the regex, since there could have been changes to it in WordPress.

**Comment by khromov** [comment]
@nikolov-tmw Thanks Nikola, don't know how I missed that! 

The PR looks solid, looking forward to it getting merged!

**Comment by danielbachhuber** [comment]
I'll see what I can do about bringing #393 over the finish line with test coverage when I have the time.

**Comment by khromov** [comment]
@nikolov-tmw  I've been looking some more at this, I don't think there's a need to bring a whole new regexp into this, as there is already a JS version of the shortcode regexp, available here:
https://github.com/WordPress/WordPress/blob/master/wp-includes/js/shortcode.js#L105

I imported it into a separate branch and the tests pass fine. We could even use the `wp.shortcode.regexp( tag )` constant, although the tests don't pass when using it (since I guess the tests don't include WP core JS functions)

**Comment by danielbachhuber** [comment]
:100: for using the JS version of shortcode regex.

@nikolov-tmw shall I leave for you to open a new PR with reasonable test coverage?

**Comment by danielbachhuber** [comment]
:ship:
