### ISSUE TITLE
Determine if Shortcake is rendering Shortcode

### ISSUE THREAD

**Issue by jakejackson1** [wp-shortcake/shortcake#399]
When doing your AJAX call to render a specific shortcode I'd love to see a `$_POST['shortcake']` option passed so we can easily handle the shortcake display a little differently than normal. 

I'm currently using `if ( isset($_POST['shortcode']) ) {` to distinguish between a standard display and a shortcake display but I could foresee some edge cases where that may cause an issue - it's unlikely but I think it's better to be specific.

**Comment by danielbachhuber** [comment]
What if you could just filter the returned preview output?

**Comment by jakejackson1** [comment]
A filter would be beneficial, although maybe not as efficient as conditionally controlling the output directly in the shortcode function. Perhaps you could also implement a constant similar to DOING_AJAX?

**Comment by khromov** [comment]
@danielbachhuber Would it perhaps be better to have a `pre_shortcake_render` filter that works like `pre_option_`, ie if something hooks onto it and returns a non-falsy value, that output is used instead.

Consider a common use case where you'd want to have a simple placeholder image for some advanced shortcodes that can't be reliably rendered in TinyMCE. Why render the shortcode, then pass the output on to the filter which we'll just override with a static image? In that case, giving the option to not even invoke the shortcode resolution may be better?

It would also be great if that filter could pass the raw shortcode string, ie `[my_shortcode param1="foo" param2="bar"]` so that you could easily use `do_shortcode()` on it yourself and optionally wrap it with some code or do something else.

**Comment by danielbachhuber** [comment]
> Would it perhaps be better to have a pre_shortcake_render filter that works like pre_option_, ie if something hooks onto it and returns a non-falsy value, that output is used instead.

I haven't ever been a fan of `pre_` filters. Generating a shortcode shouldn't be computationally complex, so you should just be able to filter after the fact.

I'd like to go down whatever route WP-API goes down https://github.com/WP-API/WP-API/issues/926

**Comment by khromov** [comment]
@danielbachhuber I'd argue there are more shortcodes that are computationally expensive than the opposite. Even built-ins like `[gallery]` makes database requests. Many use templating functions, WP_Query or even make external HTTP calls. 

Guess my point is, it's either adding a filter that can potentially save huge amounts of processing time, or choose to not offer that flexibility based on what, exactly?

**Comment by danielbachhuber** [comment]
> I'd argue there are more shortcodes that are computationally expensive than the opposite.

Then they should be cached.

> Guess my point is, it's either adding a filter that can potentially save huge amounts of processing time, or choose to not offer that flexibility based on what, exactly?

Making a decision on the implementation, and not offering a dozen different filtering options.

**Comment by khromov** [comment]
> Then they should be cached.

But there's no unified caching mechanism for shortcodes...

> Making a decision on the implementation, and not offering a dozen different filtering options.

I respect your opinion, but think it's preferable to have one too many filters than too few. Hoping we can get a unified way to detect Shortcake AJAX requests soon, guess the logic will have to be built into the shortcode, which is a shame since so many are provided by third parties.

**Comment by jakejackson1** [comment]
> I respect your opinion, but think it's preferable to have one too many filters than too few.

Agreed. WordPress got where it is today in part by how easy it is to customise by developers. More choice in this case wouldn't be a bad thing.

**Comment by bobbingwide** [comment]
can you hook into 'shortcode_ui_before_do_shortcode' action ?

**Comment by danielbachhuber** [comment]
This is now more possible with the `SHORTCODE_UI_DOING_PREVIEW` constant added in #472
