### ISSUE TITLE
New Field: Term Select

### ISSUE THREAD

**Issue by dev4press** [wp-shortcake/shortcake#415]
This field would be similar to post_select, but for terms selection.. User register the field and set the taxonomy terms can be choosen from.

**Comment by danielbachhuber** [comment]
Seems reasonable — as well as User Select

**Comment by jurajk** [comment]
would love to see both these fields in future releases.

**Comment by johnnypea** [comment]
+1

**Comment by marcusforsberg** [comment]
+1 :)

**Comment by misfist** [comment]
Taxonomy select would be super useful. +1

**Comment by mattheu** [comment]
We've got this now!

**Comment by misfist** [comment]
I have this code and the select isn't rendering.

``` php
public function image_gallery_shortcode_ui() {
    $fields = array(
        array(
            'label'    => esc_html__( 'Select Category', 'cvar-core' ),
            'attr'     => 'slug',
            'type'     => 'term_select',
            'query'    => array( 'taxonomy' => 'media_category' ),
            'multiple' => true,
        ),
    );

    /*
     * Define the Shortcode UI arguments.
     */
    $shortcode_ui_args = array(
        'label'         => esc_html__( 'Add Image Gallery', 'cvar-core' ),
        'listItemImage' => 'dashicons-format-gallery',
        'post_type'     => array( 'post', 'page' ),
        'attrs'         => $fields,
    );

    shortcode_ui_register_for_shortcode( 'image-gallery', $shortcode_ui_args );
}
```

Is there an example of this field's usage?

**Comment by BronsonQuick** [comment]
Hey @misfist trying altering:

```
'query'    => array( 'taxonomy' => 'media_category' ),
```

to:

```
 'taxonomy' => array( 'media_category' ) 
```

There's an example of this fields usage in: https://github.com/humanmade/shortcake/blob/52882de66decb6a6d5d4d4b59451dcf2f59ff3e1/dev.php#L189

I hope that helps you! 😄

**Comment by BronsonQuick** [comment]
Or if you prefer you can just do:

```
 'taxonomy' => 'media_category' 
```

**Comment by misfist** [comment]
@BronsonQuick - Yes, this totally helps! Though, I think the main problem was that I was using the [WP repo version](https://wordpress.org/plugins/shortcode-ui/) (wpackagist.org, actually) of Shortcake UI with which it didn't work. 🔢 .

I updated my composer file to source from this repo.

Thanks!

**Comment by misfist** [comment]
Is there any way to return the term slug rather than the term id?

**Comment by khromov** [comment]
@misfist The data is stored as IDs. You can use `get_term( $term_id, $taxonomy )->slug` to get the slug.

**Comment by misfist** [comment]
@khromov I need the shortcode term value returned as the slug. I'm not sure how I could accomplish that.

Also, thanks for your speedy reply!

**Comment by goldenapples** [comment]
@misfist There isn't currently a filter around how that attribute is stored on the shortcode. Your best bet, if you can't just get the slug from the term id in your shortcode callback, might be to use the term_select field, let that return the term id, and set up an event attribute callback to update a second field, which is read-only in the UI, which stores the slug that you want to use.

Not pretty, I know. What's the use case you have that saving the term id as the attribute wouldn't work for...?

**Comment by misfist** [comment]
@goldenapples Thanks for getting back! 

I'm creating shortcode UI elements for shortcodes that come with a plugin I'm using (i.e. didn't write). It expects slugs for taxonomy terms.

Sounds like populating a second field with the slug based on selection in term_select _could_ work. 

In principle, I understand how I'd do this, but in actuality... 

1. What would the field type of the second field be?
2. Are there build-in JS functions for fetching terms or do I need to use admin_ajax to do a post request?

**Comment by mattheu** [comment]
If you don't have too many terms, you could use the standard select field and build the options from get_terms, allowing you to pass the slug as the value.

**Comment by misfist** [comment]
@mattheu The number of terms will be completely variable.

I'm adding these elements so that users will have an easier time making use of the [shortcodes](http://docs.wp-event-organiser.com/shortcodes/) provided by Events Organiser (https://wordpress.org/plugins/event-organiser/). Term select will be used for venue and category, which can have multiple selections.

I think the term_select UI works well and would like to make use of it.

**Comment by goldenapples** [comment]
@misfist One thing which I recently did when faced with a similar case (I was trying to build a UI for an existing shortcode which had an attribute which expected the URL for a permalink to a post):

* used a post_select field to enable users to select a post.
* added a text field to hold the permalink
* hooked into the event attribute hook for the post select field. In that callback, make an ajax request to get the permalink of that field and set the text field with that URL. Then unset the post_select field so that it doesn't get set on the shortcode when sending to the editor.

This is not really an ideal workflow, but it's worked well enough for me when I've tried to use it. You could probably do a little better by using hidden fields. Or, if we implement a send_to_editor hook, all of the lookup could be done there transparently to the user...

**Comment by misfist** [comment]
@goldenapples Is there a hidden field type?

**Comment by lvl99** [comment]
Anyway to select which taxonomy the term is for? Or is that already given in the results of the select field?
