### ISSUE TITLE
Line breaks not working properly after editing inner_content

### ISSUE THREAD

**Issue by khromov** [wp-shortcake/shortcake#471]
Consider a simple shortcode that just prints the inner_content.

After adding it and filling out the following as the text area of inner_content and pressing "Insert element":

![screen shot 2015-09-28 at 20 12 57](https://cloud.githubusercontent.com/assets/1207507/10144347/7ecc0036-661d-11e5-8e48-115f4f178d2b.png)

The result in WYSIWYG is:
![screen shot 2015-09-28 at 20 13 02](https://cloud.githubusercontent.com/assets/1207507/10144358/8f6a33cc-661d-11e5-9fcf-1fde70ffa731.png)

After reloading the page or toggling text/visual mode, the result is:
![screen shot 2015-09-28 at 20 13 08](https://cloud.githubusercontent.com/assets/1207507/10144364/91f34a16-661d-11e5-954f-7f5396ff2677.png)

The difference is that  there are line breaks (`<br>`)  being added when reloading page or toggling visual/text, but not otherwise.

Code:

``` php
function sct_init() {
  add_shortcode( 'simple', 'sct_simple_shortcode' );

  if ( function_exists( 'shortcode_ui_register_for_shortcode' ) ) {
    shortcode_ui_register_for_shortcode(
      'simple',
      array(
        'label'         => 'Plain Content',
        'listItemImage' => 'dashicons-welcome-write-blog',
        'inner_content' => array(
          'label' => 'Content',
        ),
        'attrs'         => array(),
      )
    );
  }

}
add_action( 'init', 'sct_init', 10 );

function sct_simple_shortcode( $atts, $content = null ) {
  extract( shortcode_atts(array(), $atts, 'simple' /* Shortcode name for attribute filtering */ ) );

  return do_shortcode( $content );
}
```

**Comment by khromov** [comment]
Fixed in #498

**Comment by danielbachhuber** [comment]
Spent a little bit of time looking into this. Here's my test case:

Pull quote with multiple line breaks:

![image](https://cloud.githubusercontent.com/assets/36432/10546696/66572ec0-73e4-11e5-9122-b80fd43564cb.png)

Renders without the linebreaks:

![image](https://cloud.githubusercontent.com/assets/36432/10546701/71021dbc-73e4-11e5-89a8-f95154fa8ef0.png)

However, the preview is passed the appropriate data:

![image](https://cloud.githubusercontent.com/assets/36432/10546716/842e5ab8-73e4-11e5-980b-db23d195e717.png)

And it appears correctly in the Text editor:

![image](https://cloud.githubusercontent.com/assets/36432/10546733/9ae8db8e-73e4-11e5-99b2-ff731c8ef832.png)

But when I switch to the Visual editor, I get broken `<p>` tags:

![image](https://cloud.githubusercontent.com/assets/36432/10546748/b757465c-73e4-11e5-93a6-1c13135137d6.png)

I _think_ the bug is actually that we're running `wpautop` on the data when we shouldn't be. The shortcode callback should run `wpautop` on `$content`, if it expects the data to have linebreaks.

**Comment by danielbachhuber** [comment]
Oh. The problem is that TinyMCE is doing its own wpautop() process on the raw shortcode before we render the preview. `shortcodeViewConstructor` is supplied with:

```
[fusion-pullquote]This quote has</p>
<p>Multiple line breaks</p>
<p>Test one[/fusion-pullquote]
```

I don't think it's safe to just strip the HTML tags, because they could be valid. Rather, `wp.mce.views` should render before `wpautop` is applied, similar to how shortcodes are rendered before `wpautop` is run.

**Comment by danielbachhuber** [comment]
`wpautop` is run on `BeforeSetContent`: https://core.trac.wordpress.org/browser/tags/4.3/src/wp-includes/js/tinymce/plugins/wordpress/plugin.js#L115

mce views are rendered on `SetContent`: https://core.trac.wordpress.org/browser/tags/4.3/src/wp-includes/js/tinymce/plugins/wpview/plugin.js#L223

**Comment by danielbachhuber** [comment]
Opened a core ticket about this https://core.trac.wordpress.org/ticket/34329

**Comment by entr** [comment]
Sorry for revisiting this but is the use case with line breaks in `inner_content` supposed to work? I can't get a line break to render in Visual mode. I tried manually inserting `<br>` and wrapping content in `<p></p>` but it always renders like what @danielbachhuber showed in his tests.

![usecase](https://cloud.githubusercontent.com/assets/36432/10546701/71021dbc-73e4-11e5-89a8-f95154fa8ef0.png)
