### ISSUE TITLE
Select2 4.0 Compatibility 

### ISSUE THREAD

**Issue by rickalee** [wp-shortcake/shortcake#475]
Using Select2 4.0 in custom metabox and Shortcake appears to conflict with v4.0 as it is using v3.5.2 which Shortcake is enqueuing when using post_select field type.

Console error
`Uncaught Error: No select2/compat/initSelection`

https://select2.github.io/announcements-4.0.html

**Comment by danielbachhuber** [comment]
Hm. Not sure the best way we can support forwards compat.

**Comment by widoz** [comment]
@rickalee If you interested I solved temporary to deregister the select2 and force to enqueue the version 3.5.2. But I don't know if this can cause other issues in conjunction with other plugins. Form me I've only the fast page switch that register the select2 and everything works fine.

**Comment by mattheu** [comment]
+1 I'd like to support the newest version. I'd also like to maintain compatability with other plugins - so would be interested to see which load their own Select2, and which are using newer versions.

I know there was talk about bundling a WP version of this at some stage. Wonder what happened to that...

**Comment by grappler** [comment]
I suppose this could be closed as it is fixed https://github.com/wp-shortcake/shortcake/pull/650

**Comment by goldenapples** [comment]
I'd like to merge #666 and release a new version before calling this "done", though. Since loading the "full" version of select2 doesn't change anything here, but does include the backcompat methods that some other plugins using select2 depend on, I'd like to start loading that ratehr than the basic script which we're currently loading.
