### ISSUE TITLE
Test coverage for the JavaScripts

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#55]
Coming out of #54, we should have test coverage for the important parts.

**Comment by noppanit** [comment]
@danielbachhuber I think it's a good idea to restructure our js as well. It's 800 lines of code already. Should it be the task of this issue or it can be a separate issue?

**Comment by danielbachhuber** [comment]
> It's 800 lines of code already. Should it be the task of this issue or it can be a separate issue?

It can be the task of this issue.

**Comment by zebulonj** [comment]
@danielbachhuber @noppanit Would love to discuss what the restructuring of the JavaScript might look like. I will follow-up later with recommendations (short-term and long-term).

**Comment by noppanit** [comment]
@zebulonj sounds good look forward to your recommendations.

**Comment by zebulonj** [comment]
@danielbachhuber @noppanit Hoping to get some initial feedback on the following recommendation before you shut down for the holiday.
1. I recommend using [Require.js](http://requirejs.org/) to support modularizing the code base and to manage dependencies. The Require.js [optimizer](http://requirejs.org/docs/optimization.html) would be used to package the source into a single file, as part of the build process (along with compiling the Sass).
2. I recommend organizing components (and files) around feature oriented modules, rather than a top level organization around role (model, view, controller, template). As a code-base grows, having models, views, controllers, etc., associated with a feature (for example, 'preview') grouped together, rather than spread across 'model', 'view', and 'controller' folders makes it easier for developers to work in the code and makes it easier to reuse individual features across projects.

I will setup a skeleton of what this might look like, but wanted to get some notes up here quickly for your input.

**Comment by noppanit** [comment]
Thank you @zebulonj for the recommendation. What do you think about http://browserify.org/ vs Require.js?

Just to clarify my comment. I hit some limitation of require.js sometime when I needed to use plugin that's not require.js compatible. Also, browserify syntax is like Node.js

However, I want to here your thoughts as well.

**Comment by zebulonj** [comment]
@noppanit I don't have first-hand experience with Browserify, but based on what I've read I'd be interested in trying it. 

If this were a larger scale code base, or if this code was supporting a more complex user interface, I'd be very hesitant. On larger applications, I'd want to have the option of compiling my code into several modules so that secondary features could be loaded only as needed. Browserify only appears to support compiling a code base into a single JavaScript file, and does not appear to support any kind of asynchronous loading. Those would be essential features (in my opinion) for a large applications, but I don't think are necessary for a plugin like Shortcake.

**Comment by zebulonj** [comment]
@danielbachhuber @noppanit Is there a project you're currently using Jasmine on that I should reference for consistent setup? If not, happy to setup Jasmine the way I usually would.

**Comment by noppanit** [comment]
@zebulonj we use it internally, but I think you can set it up the way you usually would. You want to use Grunt or Gulp?

**Comment by zebulonj** [comment]
@noppanit Perhaps (this plugin is using Grunt). Upside would be easy to run tests (from the command line) and good for continuous integration (which may not be relevant in the context of this plugin). Downside would be that PhantomJS isn't necessarily representative of the actual browser. Could potential setup for both (in browser and via command line). I like to use the Karma test runner to support automatically running tests in multiple, real browsers.

What are your thoughts?

**Comment by noppanit** [comment]
It's likely that we would need both since we want to utilize CI as well as ability to run from command line.  Please feel free to use Karma and i think it's a good idea to test on real browser as well since it's involving DOM manipulation. Grunt ia also a good option for us as we have been using Grunt as well.

Best Regards,
Noppanit Charassinvichai aka Toy

twitter: @noppanit

**Comment by zebulonj** [comment]
@danielbachhuber @noppanit I've done some additional exploration of Browserify as an option for managing dependencies and building the code for distribution. Based on that exploration, I'm feeling less inclined to use it on this project. As best as I can see so far, it lacks the advantages that Require.js has in the context of dependency injection for unit testing (and may pose other challenges in the context of unit testing).

I'd like to hear what each of you think on the subject.

**Comment by danielbachhuber** [comment]
> I'd like to hear what each of you think on the subject.

I don't have strong opinions at this time — I'll defer to Toy.

**Comment by noppanit** [comment]
Actually, Browserify has dependency injection as well for testing. I think the argument between Require.js vs Browserify.js can easily turn into the argument of Grunt vs Gulp. :-) Personally, for this plugin I don't thing it's a bad idea to use Require.js because this plugin is self-contained. And it's easy to change to any other service locator framework later on. 

Here's my challenge about Require.js. 
- From my experience, the benefit of using AMD is not that much because at the end the day the project has to be compiled for single file for each page with some common module which can easily get messy for the build file to maintain, especially large project. Grunt hasn't made this one easier as well, as it's still using r.js for configuration.
- `require` other module that's not Require.js compliant is a pain especially if that module is not well structured, for example is not wrapped inside `(function() {})`. Sometimes, I have to hack around the plugin to fix the loading problem. I always encounter problem when I have to use some jQuery plugin. 
- Browserify is doing the same thing but not restrict developers to wrap the code inside `define('', function() {}`. Which can be really annoyed when Test has to be structured like that as well. As a JavaScript developer I always refer the pattern to Node.js which Browserify offers that. 
- The build file for Browserify to build and pack everything is easier just one line of code in `Gruntfile.js`

**Comment by zebulonj** [comment]
@noppanit Thanks. Like I said, I don't have any first-hand experience with Browserify. I'd be grateful if you could point me toward a concise example of dependency injection with Browserify (whether in the test context or not).

**Comment by noppanit** [comment]
@danielbachhuber I believe this can be closed?

**Comment by danielbachhuber** [comment]
Yep, we've got good coverage now :)
