### ISSUE TITLE
Attributes showing as empty?

### ISSUE THREAD

**Issue by stevenvachon** [wp-shortcake/shortcake#598]
``` php
add_action('init', function()
{
  add_shortcode('banner', function($attrs, $content)
  {
    print_r($attrs);

    $attrs = shortcode_atts(
      [
        'background-image' => '',
        'role' => 'banner',
        'style' => ''
      ],
      $attrs,
      'banner'
    );

    print_r($attrs);

    return '';
  });



  if (function_exists('shortcode_ui_register_for_shortcode'))
  {
    shortcode_ui_register_for_shortcode('banner', [
      'label' => 'Banner',
      'post_type' => ['page'],
      'inner_content' => [
        'label' => 'Content',
        'description' => 'Can contain HTML and shortcodes.'
      ],
      'attrs' => [
        [
          'label' => 'Background Image',
          'attr' => 'background-image',
          'type' => 'attachment',
          'libraryType' => ['image'],
          'addButton' => 'Select Image',
          'frameTitle' => 'Select Background Image'
        ]
      ]
    ]);
  }
});
```

``` text
[banner background-image="1234"][/banner]
```

The live site prints:

```
Array ( [background-image] => 1234 )
Array ( [background-image] => 1234 [role] => banner [style] => )
```

and in TinyMCE it prints:

```
Array ( [background-image] => [role] => banner [style] => ) 
```

Is there something that I'm doing incorrectly?

**Comment by stevenvachon** [comment]
K, it's this #495

**Comment by goldenapples** [comment]
> Is there something that I'm doing incorrectly?

No, I don't think you're doing anything incorrectly in the shortcode registration, just that the debug code in your shortcode callback is printing, rather than returning its value as a shortcode callback should.

This might work for debugging in the front-end, but the Shortcake preview is returned inside a JSON Ajax response, so printing output is going to end badly.

Changed your shortcode callback to return the value you were trying to test, like `return print_r( $attrs, true );`, and it looks like I imagine you'd expect:

<img width="967" alt="screen shot 2016-04-30 at 6 10 59 pm" src="https://cloud.githubusercontent.com/assets/665992/14939329/32aae45c-0eff-11e6-9b6d-a601a42b780e.png">

**Comment by stevenvachon** [comment]
I'd had `if (!empty($attrs['background-image']))` that was failing, so it wasn't a printing issue. Renaming my attribute to `background_image` fixed it. As pointed out, it's related to #495 -- I have not yet updated WordPress beyond 4.3.2
