### ISSUE TITLE
Update Select2 from 3.5.2 to 4.0.3 (or add compat)

### ISSUE THREAD

**Issue by westonruter** [wp-shortcake/shortcake#646]
The Customize Posts plugin includes Select2 4.0.3 and it seems that Shortcake is calling a Select2 method that no longer available: https://wordpress.org/support/topic/conflict-with-shortcake-ui/

So can Select2 be upgraded in Shortcake? Or can Shortcake add compatibility for v4?

**Comment by goldenapples** [comment]
Seems like the main thing we'll need to rewrite for this to work on Select2 4.0.3 is the `initSelection` method used to set the initial data values of the attribute fields which are rendered with select2 elements.

Since that method has been [removed in the latest Select2](https://select2.github.io/announcements-4.0.html#removed-initselection), we'll need to override the `current` method of the data adapter to properly set the selected options.

**Comment by goldenapples** [comment]
Fixed in latest version.
