### ISSUE TITLE
Need Shortcode for Gallery, multiple ID's and images in one field

### ISSUE THREAD

**Issue by ameshkin** [wp-shortcake/shortcake#647]
Someone had a pull request for a feature that basically enabled a gallery. I tried using that code but it was too outdated and out of sync with master.

I'm thinking of forking and adding this unless someone else has a solution.

**Comment by goldenapples** [comment]
I'd like to see this in a version 0.7.0 since the code is available and we need to get a new release out soon anyways.

**Comment by davidvexel** [comment]
@goldenapples do you have an approximate date for next stable release, I'm looking forward to use the new features!

**Comment by goldenapples** [comment]
#508, enabling a gallery-type field, just needs to be refreshed. In the last discussion, @mattheu was going to take that on. We're targeting next week - week of 11/7 - for the next release, and that PR is scheduled for inclusion. I'll leave this issue open so that we can attach the PR to an issue for tracking.

**Comment by mattheu** [comment]
Yeah I'm going to do this tomorrow :)

**Comment by goldenapples** [comment]
This is resolved with #508, which was just merged and will be available in the next stable release.
