### ISSUE TITLE
Embed Video (ARVE) and Add Post Element buttons do not work

### ISSUE THREAD

**Issue by nickmarti** [wp-shortcake/shortcake#665]
After the last update, Embed Video (ARVE) button (from ARVE Advanced Responsive Video Embedder) does not work in editor mode of my WordPress theme. Please provide me with the link of your plugin’s Version 0.7.0-alpha. I had no problems with that version. 

Thank you.

**Comment by goldenapples** [comment]
Question - what version of ARVE are you trying it with? And do you have any other plugins installed?

I just installed Shortcake 0.7.0 and ARVE 7.9.20 on a fresh WordPress install with twentysixteen theme, and I don't see any problems with the two together:

![arve_shortcake](https://cloud.githubusercontent.com/assets/665992/20734245/15abcbc8-b64d-11e6-83ab-0cdff4d1ef44.gif)

**Comment by nickmarti** [comment]
Hi Nathaniel,

Thank you for your prompt reply. Apparently, the latest version of
Shortcake does collide with some of the other plugins I have installed (the
list below), not necessarily with ARVE 7.9.2. Even if I find the plugin in
question I probably don't want to uninstall it. As I said, Shortcake's
version 0.7.0-alpha worked well with my already installed plugins.


   - ARVE Advanced Responsive Video Embedder7.9.20
   - Autoptimize2.1.0
   - Content.ad1.1.16
   - Crafty Social Buttons1.5.5
   - Disable Emojis1.5.2
   - EWWW Image Optimizer3.1.3
   - Gallery by BestWebSoft4.4.6
   - Google Analytics by BestWebSoft1.7.0
   - Heartbeat Control1.0.3
   - Lazy Load0.6.1
   - Login LockDownv1.7.1
   - Remove Comment Website/URL Box1.0
   - SB-RSS_feed-plus1.4.18
   - Social Media Auto Publish1.7
   - WP-PostViews1.73
   - WP-Sweep1.0.8
   - WP Super Cache1.4.8


On Wed, Nov 30, 2016 at 1:01 AM, Nathaniel Taintor <notifications@github.com

**Comment by goldenapples** [comment]
OK. I pushed up a tag with the plugin as it was before the update to the select2 library: https://github.com/wp-shortcake/shortcake/releases/tag/v0.7.0-pre

Does that work with your existing plugins?

**Comment by nickmarti** [comment]
I am not sure because the last version of Shortcake plugin that worked on
my site was titled "0.7.0-alpha" [Shortcake (Shortcode UI) Version
0.7.0-alpha]. Nicolas Jonas attached the download link of that version to
previous version of his ARVE plugin. However, this version of Shortcake
plugin is titled "v0.7.0-pre".

On Wed, Nov 30, 2016 at 5:49 PM, Nathaniel Taintor <notifications@github.com

**Comment by goldenapples** [comment]
> last version of Shortcake plugin that worked on my site was titled "0.7.0-alpha"

I'd try this one anyways. The version number in the plugin has been 0.7.0-alpha for a long time; ever since development on the 0.7.0 release began about a year ago. This is a fairly recent snapshot, from right before the updates to the select2 library - which seems to be the change in 0.7.0 which breaks a lot of compatibility - were merged.

**Comment by nextgenthemes** [comment]
Hi, author of ARVE here. I just want to note that the version I marked as 0.7.0-alpha was just a snapshot or some at that point latest Github version of Shortcake UI because I was waiting for a update that was not coming.

I [re-uploaded this](http://nextgenthemes.com/shortcode-ui-0.7.0-alpha.zip) from a backup to my site now, I thought its no longer needed. I hope this helps.

I use this code to open the dialog. https://github.com/nextgenthemes/advanced-responsive-video-embedder/blob/beta/admin/arve-admin.js#L89-L105

**Comment by nickmarti** [comment]
Wow! Thank you!

**Comment by nickmarti** [comment]
Thanks for clarification. I just want to inform you that the author of ARVE
re-uploaded the version he marked as 0.7.0-alpha, which was the latest
Github version of Shortcake at that point.

On Wed, Nov 30, 2016 at 8:19 PM, Nathaniel Taintor <notifications@github.com

**Comment by goldenapples** [comment]
Thanks @nextgenthemes for uploading that.

I'll mark an action item to search through the plugin repository and find any plugins which are using older versions of select2. It might be good to maintain a list of potential conflicts in the wiki here. At the very least, it'd be interesting to know how widespread the potential for conflicts is.
