### ISSUE TITLE
Initial value not inserted in shortcode for select fields

### ISSUE THREAD

**Issue by MickeyKay** [wp-shortcake/shortcake#668]
Summary: when initially saving inserting a shortcake component, if no fields are changed, none of them are actually inserted into the shortcode. This is an issue since it makes it problematic to save default values.

Screencast example:
![dykibkq3ar](https://cloud.githubusercontent.com/assets/3189678/20807577/64700c5c-b7b4-11e6-8b71-4c1183a558f5.gif)

Doesn't seem like a huge deal, however this cause problems re: changing defaults later on. For example, right now the first value in the template dropdown in the example above is "Simple", which is essentially the default value. If, however, later on behind the scenes we want to switch our default template behind the scenes, this _will_ affect all components that were only saved once (and hence have no `template` attribute, however it will not affect any component that has been updated at least once. So while the UI looks exactly the same for two saved components, one can actually have the `template` att specified, while the other might not, and thus when the behind-the-scenes default is changed, the two components that look exactly the same from the UI perspective will actually render differently, which is not great.

Is this functionality intended, and if so, why? If not, can we get a fix please?

**Comment by goldenapples** [comment]
> Is this functionality intended, and if so, why?

Hmm. The obvious way around this from the user side is to explicitly set the default value. Depending on the first option in the select field to be the default is less than ideal - among other reasons since there are some back-compatability cases where the order of the elements in the select field are undefined (see #620).

Functionally, it would seem that a select field with no value set shouldn't set the attribute value on the shortcode. 

Maybe a good way around that would be to automatically add a blank option to select fields where there's no default set? Or just to treat the first item in the list as the default value if no default is specified?

**Comment by MickeyKay** [comment]
Right, that's what we've done in the past, however aside from backwards-compatibility issues (which are understandable dealbreakers for changing this functionality), this requires more work on the developers part since now we need to specify value in two places (both the select list, as well as a default somewhere, whether as the `value` att, or in some behind-the-scenes functionality. Anyhow, I get why the existing method might be preferable in terms of allowing for more explicit, opt-in control of defaults. Thanks!
