### ISSUE TITLE
Unstralatable string "Thumbnail Details"

### ISSUE THREAD

**Issue by zedejose** [wp-shortcake/shortcake#716]
In https://github.com/wp-shortcake/shortcake/blob/master/inc/fields/class-shortcode-ui-field-attachment.php#L138 the string is not gettexted, making it untranslatable:

<img width="474" alt="screen shot 2017-04-03 at 14 41 43" src="https://cloud.githubusercontent.com/assets/1371600/24611946/b6345304-187b-11e7-816b-bcf3d8994bd3.png">

Also, and this is a doubt more than an issue, maybe it shouldn't say "*Thumbnail* Details" at all. Since it is consistently referred to as an "attachment" everywhere else, maybe it should read "*Attachment* Details"

**Comment by goldenapples** [comment]
Thanks for pointing that out. It also looks like the "Edit Attachment" link text in that same container is also not gettexted, which should also be fixed.

I also agree that "Attachment Details" makes more sense in that text than "Thumbnail Details", especially because that same label is shown for non-image attachments.

Here, for example, "Thumbnail" doesn't make any sense, since there's no thumbnail displayed:
![screenshot from 2017-04-04 10-55-46](https://cloud.githubusercontent.com/assets/665992/24671118/52124228-1925-11e7-8063-9c5bb527e71f.png)
