### ISSUE TITLE
Show post type in post_select field

### ISSUE THREAD

**Issue by grappler** [wp-shortcake/shortcake#735]
Related to #627

I have been using `post_select` for a client and they we were querying posts from two post types. The posts in both post types had the same titles. There was no way to differentiate between the two posts.

![image](https://cloud.githubusercontent.com/assets/1785641/26061497/66b2dc96-3988-11e7-8416-d604a41a8bc9.png)

[Customize Object Selector](https://github.com/xwp/wp-customize-object-selector) has a feature where it shows the post type.
![image](https://cloud.githubusercontent.com/assets/1785641/26061356/057117fe-3988-11e7-9d22-908a6fe8164f.png)

Beitrag = Post
Inhaltselement = Content Block (CPT)

**Comment by goldenapples** [comment]
Good suggestion, and I like the fix you proposed for it (showing the post type object label in parentheses if more than one post type is being queried).

In order to accommodate more customization of the templated results (for requests like #627, where the idea of adding the post featured image to the dropdown was proposed), we might have to add a filter in the loop that handles the formatting of each post in the ajax return value - because it would be a two-part process, returning additional fields for each post in the ajax response, and then defining a `templateSelection` method on the select2 field to render it.

This is a good fix for the basic requirement here, though.

**Comment by grappler** [comment]
Perhaps we can think about adding support for post statuses too. `term_select` could profit from some of these changes too.

> Good suggestion, and I like the fix you proposed for it (showing the post type object label in parentheses if more than one post type is being queried).

I can't take all of the credit. Got my inspiration from @westonruter

**Comment by goldenapples** [comment]
> `term_select` could profit from some of these changes too.

Yeah, that follows the same pattern as post type -- maybe just including the taxonomy name in parentheses when more that one taxonomy is queried -- and would make sense to tackle in the same way.

> Perhaps we can think about adding support for post statuses too.

I think that might be adding too much information to an unstructured UI. I've worked on setups where that would be helpful, but it would be hard to make that decision from the plugin. Maybe something that might be better done by adding a filter?
